using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BrokenKaraokeData : MonoBehaviour {
    public string[] songStrings = new string[] {"ALLCALMAPA",
"IHTDETSHOW",
"ATSTTCTBIT",
"DYHTPSSTSO",
"IILHTWYSRM",
"IDCIMBTGAW",
"TAHIYLYWKA",
"TAPIYHAIKT",
"HIMIWWIAAT",
"SOYSWNTTHW",
"NCTYTOOSWS",
"TOYSINETMB",
"IFALFMDJDR",
"ICTDFMSWFT",
"INMDALLINT",
"SSIGUOYIBT",
"WIHTSWTWCD",
"IYCYMITFIL",
"MLGHSTGAAF",
"WTAIDKWITS",
"SOTEOFATSO",
"WKWTBIAWFH",
"TNTFUTNPFU",
"YMTNNTFDIS",
"YGYHTMATYS",
"ICTTNNTBAA",
"FJASATGWDO",
"TCWIBATSAG",
"AYHUASOYWI",
"TSTBSACTST",
"IWCEBITDTA",
"ICTICOIBAL",
"WTSBTSOWHJ",
"OOATRYKYTM",
"SIFAAMCPHF",
"IRLCISIKBI",
"IDHFCOICWT",
"HTHASGTTNK",
"LCIGYMHBTV",
"OTWOIFBTFI",
"WTMCSILTTY",
"OMKISGTTBT",
"SNHNAICAIB",
"IDWALFCTIJ",
"YBWOYBNCYB",
"OILTRAYSAW",
"PDTCALTMIT",
"SFIGOAIOTD",
"IGYMWYSBYM",
"FTLTTNYWNT",
"ETABADITEO",
"BSJROMMAIC",
"BIBYDOMBKO",
"ISAMGHTDWA",
"TOYCAMSIPD",
"ATLGABLTWC",
"MIATHTHNLN",
"LICCLTMYDC",
"IWJATMALTM",
"YVNSCIDSGF",
"BIBSWYSOWW",
"YHCTSWRLHL",
"IDATDABOTP",
"PTTAAVOLWT",
"TGAWGFTSEH" };
public string[] songNames = new string[] {"ALITTLELESSCONVERSATION",
"AFRICA",
"ALLTHESMALLTHINGS",
"DOYOUHEARTHEPEOPLESING",
"FREEBIRD",
"FRIDAYIMINLOVE",
"GOODBYEMRA",
"HEALTHEWORLD",
"HELLO",
"HOWTOSAVEALIFE",
"MAKEYOUROWNKINDOFMUSIC",
"OHMYGOD",
"PERFECT",
"PURESHORES",
"SAVEROCKNROLL",
"SAYSOMETHING",
"SKIN",
"TAKEACHANCEONME",
"TAKEMETOCHURCH",
"TAKEONME",
"THEFLOOD",
"UPWHEREWEBELONG",
"WHOWANTSTOLIVEFOREVER",
"YMCA",
"YOUDONTKNOWME",
"FEEDTHEWORLDDOTHEYKNOWITSCHRISTMAS",
"CHRISTMASTIMEDONTLETTHEBELLSEND",
"ALLALONEONCHRISTMAS",
"MERRYCHRISTMASEVERYBODY",
"IBELIEVEINFATHERCHRISTMAS",
"FAIRYTALEOFNEWYORK",
"ITSNEVERGONNASNOWATCHRISTMAS",
"IWISHITCOULDBECHRISTMASEVERYDAY",
"RUNRUDOLPHRUN",
"MERRYCHRISTMASEVERYONE",
"WHITEWINEINTHESUN",
"DRIVINGHOMEFORCHRISTMAS",
"HARKTHEHERALDANGELSSING",
"LASTCHRISTMAS",
"LETITSNOW",
"STEPINTOCHRISTMAS",
"MANWITHTHEBAG",
"SILENTNIGHT",
"ALLIWANTFORCHRISTMASISYOU",
"SANTACLAUSISCOMINGTOTOWN",
"JACKSONPARKEXPRESS",
"DARETOBESTUPID",
"ALBUQUERQUE",
"IFTHATISNTLOVE",
"SLIMECREATURESFROMOUTERSPACE",
"CHRISTMASATGROUNDZERO",
"ONEOFTHOSEDAYS",
"DONTWEARTHOSESHOES",
"MYOWNEYES",
"VIRUSALERT",
"WEASELSTOMPINGDAY",
"BOB",
"WORDCRIMES",
"EVERYTHINGYOUKNOWISWRONG",
"THENIGHTSANTAWENTCRAZY",
"JERRYSPRINGER",
"PRETTYFLYFORARABBI",
"TRUCKDRIVINSONG",
"THATSYOURHOROSCOPEFORTODAY",
"HARDWARESTORE" };
    public string[] songNamesLogging = new string[] {
"A Little Less Conversation",
"Africa",
"All the Small Things",
"Do You Hear the People Sing?",
"Free Bird",
"Friday I'm in Love",
"Goodbye Mr. A",
"Heal the World ",
"Hello",
"How to Save a Life",
"Make Your Own Kind of Music",
"Oh My God",
"Perfect",
"Pure Shores",
"Save Rock'n'Roll",
"Say Something",
"Skin",
"Take a Chance on Me",
"Take Me to Church",
"Take on Me",
"The Flood",
"Up Where We Belong",
"Who Wants to Live Forever? ",
"Y.M.C.A",
"You Don't Know Me",
"Feed the World (Do They Know It's Christmas?)",
"Christmas Time (Don't Let the Bells End)",
"All Alone on Christmas ",
"Merry Christmas Everybody",
"I Believe in Father Christmas",
"Fairytale of New York",
"It's Never Gonna Snow (At Christmas)",
"I Wish it Could be Christmas Every Day",
"Run Rudolph, Run",
"Merry Christmas Everyone",
"White Wine in the Sun ",
"Driving Home for Christmas",
"Hark! The Herald Angels Sing",
"Last Christmas",
"Let it Snow",
"Step into Christmas",
"Man With the Bag ",
"Silent Night",
"All I Want for Christmas is You",
"Santa Claus is Coming to Town",
"Jackson Park Express",
"Dare to be Stupid",
"Albuquerque",
"If That Isn’t Love",
"Slime Creatures from Outer Space",
"Christmas at Ground Zero",
"One of Those Days",
"Don’t Wear Those Shoes",
"My Own Eyes",
"Virus Alert",
"Weasel Stomping Day",
"Bob",
"Word Crimes",
"Everything You Know Is Wrong",
"The Night Santa Went Crazy",
"Jerry Springer",
"Pretty Fly for a Rabbi",
"Truck Drivin’ Song",
"That’s Your Horoscope for Today",
"Hardware Store"};
}
